Update network utilities - New functionality - WIP
YangLab-um/BiologicalOscillations.jl pull request #22
Opened 2023-08-24 20:17 UTC by ftavella

In this PR:
- Consider edge cases on network comparison to speed up calculation
- Implement a new function to count the number of coherent and incoherent inputs

2023-09-14 18:37 UTC, biphy requested changes

2023-09-14 18:37 UTC, biphy commented on src/network_utilities.jl
> +    coherence = DataFrame(coherent = coherent, incoherent = incoherent)
Is there a reference for this definition of coherence? According to [this paper](https://www.cell.com/cell-systems/pdf/S2405-4712(17)30287-9.pdf), I was thinking that a node is coherent if and only if all the inputs (more than one) have the same sign.

2023-09-14 18:37 UTC, biphy commented on src/network_utilities.jl
> +        next_node = findall(connectivity[next_node, :] .!= 0)[1]
I believe there could be multiple cycles that extend from a given edge. The following is an example:
```julia
calculate_loop_length_and_type([0 0 0 1 1; 1 0 0 0 0; 1 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0], [3, 1])
```
For this connectivity matrix, there are two loops that include the given 1->3 edge: 1-3-4-1 (length 3), 1-3-4-5-1 (length 4). But the current implementation detects only one of them.

In [this PR](https://github.com/YangLab-um/BiologicalOscillations.jl/pull/25), I am working on a function that finds all cycles in any arbitrary connectivity matrix. The function does exhausive search of all possible cycles and thus has very bad efficiency (O(n!) time complexity), but it might be used as an alternative as long as we are interested in small networks.

2023-09-14 18:41 UTC, ftavella commented on src/network_utilities.jl
> +    coherence = DataFrame(coherent = coherent, incoherent = incoherent)
That's a great idea for multiple inputs (more than two). I'm going to specify that this function is only for single additions to a negative-feedback-only network

2023-09-14 18:46 UTC, ftavella commented on src/network_utilities.jl
> +        next_node = findall(connectivity[next_node, :] .!= 0)[1]
Perfect! I will remove this function and we will use yours moving forward

2023-09-14 20:07 UTC, ftavella commented on src/network_utilities.jl
> +    coherence = DataFrame(coherent = coherent, incoherent = incoherent)
Thinking this again. I will implement what you suggest so we have it in this PR! I'm going to change the return type to be a string.

2023-09-15 20:45 UTC, biphy approved these changes
Nice update!

2023-09-15 20:45 UTC, biphy commented on test/network_utilities_tests.jl
I will rewrite the deleted tests (the ones testing `calculate_loop_length_and_type`) using the function introduced in PR [#25](https://github.com/YangLab-um/BiologicalOscillations.jl/pull/25).

2023-09-15 20:45 UTC, merged